services:
    server:
        container_name: vaultwarden
        environment:
            - ADMIN_TOKEN= REPLACE WITH SECURE PASSWORD!
            - SIGNUPS_ALLOWED=false
        volumes:
            - /mnt/remaining/bitwarden/data/:/data/
        ports:
            - 3002:80
        image: vaultwarden/server:latest
        restart: unless-stopped