services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "192.168.178.151:53:53/udp"
      - "3008:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'REPLACE WITH SECURE PASSWORD'
    volumes:
      - '/mnt/remaining/pihole/etc-pihole:/etc/pihole'
      - '/mnt/remaining/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped