services:
  grafana:
    network_mode: "host"
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    user: 1000:1000
    environment:
     - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
     - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
     - /mnt/remaining/grafana:/var/lib/grafana
  prometheus:
    network_mode: "host"
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /mnt/remaining/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=1y'