global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: docker
    scrape_interval: 120s
    scrape_timeout: 10s
    metrics_path: /metrics
    static_configs:
      - targets:
         - localhost:9323
  - job_name: dockercustom
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /docker
    static_configs:
      - targets:
         - localhost:1234
  - job_name: jellyfinitems
    scrape_interval: 1d
    scrape_timeout: 10s
    metrics_path: /jf_items
    static_configs:
      - targets:
         - localhost:1234
  - job_name: jellyfinsessions
    scrape_interval: 30s
    scrape_timeout: 20s
    metrics_path: /jf_sessions
    static_configs:
      - targets:
         - localhost:1234
  - job_name: cpu
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /cpu
    static_configs:
      - targets:
         - localhost:1234
  - job_name: disk
    scrape_interval: 120s
    scrape_timeout: 10s
    metrics_path: /disk
    static_configs:
      - targets:
         - localhost:1234
  - job_name: memory
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /memory
    static_configs:
      - targets:
         - localhost:1234
  - job_name: temprature
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /temp
    static_configs:
      - targets:
         - localhost:1234